apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    app: {{ .Chart.Name }}
    imageTag: {{ .Values.imageTag }}
    team: {{ .Values.team }}
    slack: {{ .Values.slack }}
    type: {{ .Values.type }}
    environment: {{ .Release.Namespace }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: {{ .Release.Name }}-circleci-demo
  ports:
  - name: apache-port
    port: 80
    targetPort: {{ .Values.service.internalPort }}
