aliases:
  - &GCP-auth
    name: GCP Authentication
    command: |
      echo $GCLOUD_SERVICE_KEY > ${HOME}/account-auth.json
      gcloud auth activate-service-account --key-file ${HOME}/account-auth.json
      gcloud --quiet container clusters get-credentials $CLOUDSDK_CONTAINER_CLUSTER

  - &create-image
    name: Create Docker image
    command: |
      echo "creating image $CIRCLE_BRANCH-v$VERSION"
      docker build -t eu.gcr.io/fagdag-devops/$CIRCLE_PROJECT_REPONAME:$CIRCLE_BRANCH-v$VERSION .

  - &upload-image
    name: Upload image to GCR
    command: |
      docker login -u _json_key --password-stdin https://eu.gcr.io < ${HOME}/account-auth.json
      docker push eu.gcr.io/fagdag-devops/$CIRCLE_PROJECT_REPONAME:$CIRCLE_BRANCH-v$VERSION

#  - &install-helm
#    name: Install Helm
#    command: |
#      HELM_VER="helm-v2.10.0-linux-amd64"
#      curl -L -o /tmp/$HELM_VER.tar.gz https://storage.googleapis.com/kubernetes-helm/$HELM_VER.tar.gz
#      tar -zxv -C /tmp -f /tmp/$HELM_VER.tar.gz
#      mv /tmp/linux-amd64/helm /usr/local/bin/helm
#      helm init --client-only
#      helm plugin install https://github.com/viglesiasce/helm-gcs.git --version v0.2.0
#      helm repo add entur-rtd-repo gs://entur-helm-charts

#  - &update-and-package-helm-chart
#    name: Update helm chart with new version
#    command: |
#      sed -i "s/version:.*$/version: '$VERSION'/g"  ./circleci-demo/Chart.yaml
#      sed -i "s/appVersion:.*$/appVersion: '$CIRCLE_BRANCH-v$VERSION'/g"  ./circleci-demo/Chart.yaml
#      sed -i "s/name:.*$/name: 'circleci-demo-$CIRCLE_BRANCH'/g"  ./circleci-demo/Chart.yaml
#      sed -i "s/imageTag:.*$/imageTag: '$CIRCLE_BRANCH-v$VERSION'/g"  ./circleci-demo/values.yaml
#      mv circleci-demo circleci-demo-$CIRCLE_BRANCH
#      cat ./circleci-demo-$CIRCLE_BRANCH/Chart.yaml
#      helm package ./circleci-demo-$CIRCLE_BRANCH
#      helm gcs push circleci-demo-$CIRCLE_BRANCH-$VERSION.tgz gs://entur-helm-charts
#
#  - &push-helm-chart-master
#      helm gcs push products-chart-$VERSION.tgz gs://entur-helm-charts
#
#  - &push-helm-chart-feature
#      helm gcs push products-chart-$CIRCLE_BRANCH-$VERSION.tgz gs://entur-helm-charts
#
#  - &google-sdk-container-config
#    docker:
#    - image: google/cloud-sdk:latest
#      environment:
#        TERM: dumb

executors:
  java:
    docker:
    - image: circleci/openjdk:8
      environment:
        TERM: dumb


version: 2.1
jobs:
  build:
    executor: java
    steps:
#      - add_ssh_keys:
#          fingerprints:
#          - $SSH_FINGERPRINT
      - checkout
      - run: *create-image
      - run: *GCP-auth
  masterjob:
    executor: java

    steps:
      - run: echo deploy


workflows:
  main:
    jobs:
      - build:
          context: global
      - masterjob
