apiVersion: v1
kind: Service
metadata:
# # enable if you want prometheus logging
#   annotations:
#     prometheus.io/port: "9779"
#     prometheus.io/scrape: "true"
  labels:
    name: circleci-demo
  name: circleci-demo
  namespace: rtd
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 5000
  selector:
    name: circleci-demo
  sessionAffinity: None
  type: ClusterIP
